name: .NET

on: [ push, pull_request ]

jobs:
  strategy:
    matrix:
      os: [ macos-latest, ubuntu-latest, windows-latest ]
      dotnet-version: [ '5.0.x' ]
  runs-on: ${{ matrix.os }}
  build:
    steps:    
    - uses: actions/checkout@v2
    - name: Setup .NET SDK on system ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
